# Generated by Django 2.1.2 on 2018-11-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='creator',
        ),
    ]
