# Generated by Django 2.1.2 on 2018-11-16 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='organizations_father', to=settings.AUTH_USER_MODEL),
        ),
    ]
